project: "test"

project_folder: 'test/'

fastq: 'fastq/'

# Alternatively, fastqs can be specified as either paths relative to the 
# project folder or as absolute paths.
#fastq:
#    MATalpha_R1:
#        lane1:
#            - fastq/MATalpha_R1/lane1/SRR2601842_1.fastq.gz
#            - fastq/MATalpha_R1/lane1/SRR2601842_2.fastq.gz
#        lane2:
#            - fastq/MATalpha_R1/lane2/SRR2601843_1.fastq.gz
#            - fastq/MATalpha_R1/lane2/SRR2601843_2.fastq.gz
#    MATalpha_R2:
#        lane1:
#            - fastq/MATalpha_R2/lane1/SRR2601845_1.fastq.gz
#            - fastq/MATalpha_R2/lane1/SRR2601845_2.fastq.gz
#    MATa_R1:
#        lane1:
#            - fastq/MATa_R1/lane1/SRR2601848_1.fastq.gz
#            - fastq/MATa_R1/lane1/SRR2601848_2.fastq.gz
#    MATa_R2:
#        lane1:
#            - fastq/MATa_R2/lane1/SRR2601851_1.fastq.gz
#            - fastq/MATa_R2/lane1/SRR2601851_2.fastq.gz

library_groups:
    MATalpha:
        - MATalpha_R1
        - MATalpha_R2
    MATa:
        - MATa_R1
        - MATa_R2
    all:
        - MATa_R1
        - MATa_R2
        - MATalpha_R1
        - MATalpha_R2

library_name_sep: "-"

genome:
    name: 'sacCer3'
    fasta_path: 'genome/sacCer3.fa.gz'
    chrom_sizes_path: 'genome/sacCer3.chrom.sizes'

cooler_resolutions:
    - 1000000
    - 400000
    - 200000
    - 100000
    - 40000
    - 20000
    - 10000
