name: distiller
channels:
    - conda-forge               
    - defaults                  
    - bioconda                  
    - golobor
dependencies:
    - python=3.4   # or 2.7
    - pairix
    - setuptools 
    - pip
    - cython 
    - numpy 
    - nose 
    - pbgzip
    - sra-tools 
    - pip:
        - git+git://github.com/mirnylab/pairsamtools
